# coding: utf-8

"""
    elepay API リファレンス

    elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@elestyle.jp
    Generated by: https://openapi-generator.tech
"""

from elepay.paths.charges_id_capture.post import CaptureCharge
from elepay.paths.charges.post import CreateCharge
from elepay.paths.charges.get import ListCharges
from elepay.paths.charges_id.get import RetrieveCharge
from elepay.paths.charges_id_status.get import RetrieveChargeStatus
from elepay.paths.charges_id_revoke.post import RevokeCharge


class ChargeApi(
    CaptureCharge,
    CreateCharge,
    ListCharges,
    RetrieveCharge,
    RetrieveChargeStatus,
    RevokeCharge,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
