# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import elepay
from elepay.paths.charges_id_refunds import post  # noqa: E501
from elepay import configuration, schemas, api_client

from .. import ApiTestMixin


class TestChargesIdRefunds(ApiTestMixin, unittest.TestCase):
    """
    ChargesIdRefunds unit test stubs
        Create refund  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 201






if __name__ == '__main__':
    unittest.main()
