# coding: utf-8

"""
    elepay API リファレンス

    elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。   # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class RefundsResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'total': 'int',
        'refunds': 'list[RefundDto]',
        'error': 'ElepayRestError'
    }

    attribute_map = {
        'total': 'total',
        'refunds': 'refunds',
        'error': 'error'
    }

    def __init__(self, total=None, refunds=None, error=None):  # noqa: E501
        """RefundsResponse - a model defined in OpenAPI"""  # noqa: E501

        self._total = None
        self._refunds = None
        self._error = None
        self.discriminator = None

        if total is not None:
            self.total = total
        if refunds is not None:
            self.refunds = refunds
        if error is not None:
            self.error = error

    @property
    def total(self):
        """Gets the total of this RefundsResponse.  # noqa: E501

        件数  # noqa: E501

        :return: The total of this RefundsResponse.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this RefundsResponse.

        件数  # noqa: E501

        :param total: The total of this RefundsResponse.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def refunds(self):
        """Gets the refunds of this RefundsResponse.  # noqa: E501

        返金詳細内容  # noqa: E501

        :return: The refunds of this RefundsResponse.  # noqa: E501
        :rtype: list[RefundDto]
        """
        return self._refunds

    @refunds.setter
    def refunds(self, refunds):
        """Sets the refunds of this RefundsResponse.

        返金詳細内容  # noqa: E501

        :param refunds: The refunds of this RefundsResponse.  # noqa: E501
        :type: list[RefundDto]
        """

        self._refunds = refunds

    @property
    def error(self):
        """Gets the error of this RefundsResponse.  # noqa: E501


        :return: The error of this RefundsResponse.  # noqa: E501
        :rtype: ElepayRestError
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this RefundsResponse.


        :param error: The error of this RefundsResponse.  # noqa: E501
        :type: ElepayRestError
        """

        self._error = error

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RefundsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
