# coding: utf-8

"""
    elepay API リファレンス

    elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: support@elestyle.jp
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from elepay import schemas  # noqa: F401


class SubscriptionStatusType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    定期課金ステータス
- new 新規
- active 有効
- past_due 延滞中
- canceled 取消済み

    """


    class MetaOapg:
        enum_value_to_name = {
            "new": "NEW",
            "active": "ACTIVE",
            "past_due": "PAST_DUE",
            "canceled": "CANCELED",
        }
    
    @schemas.classproperty
    def NEW(cls):
        return cls("new")
    
    @schemas.classproperty
    def ACTIVE(cls):
        return cls("active")
    
    @schemas.classproperty
    def PAST_DUE(cls):
        return cls("past_due")
    
    @schemas.classproperty
    def CANCELED(cls):
        return cls("canceled")
